services:
  app:
    build:
      context: .
    container_name: app
    ports:
      - '5000:5000'
    environment:
      FLASK_ENV: testing
      MYSQL_HOST: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_DB: mysql_user_auth
    depends_on:
      - db

  db:
    image: mysql:8.0.36
    container_name: db
    cap_add:
      - SYS_NICE
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql_user_auth
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
