name: Commit Stage
on: push

env:
  MYSQL_USER: admin
  MYSQL_PASSWORD: admin123
  MYSQL_DB: mysql_user_auth

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with unittest
        run: |
          coverage run -m unittest discover
